apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: multi-k8s-com-tls
spec:
    secretName: multi-k8s-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: bets4me.net
    dnsNames:
        - bets4me.net
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - bets4me.net